### ISSUE TITLE
help with pi temp flashing 

### ISSUE THREAD

**Issue by Sarah-1331** [Rikkert-RS/VenusOS-TemperatureService#13]
i have installed latest version 
Thank you for your addition to the community 

i have not installed anything except guimodes and setup helper 

raspberry pi 3 keeps flashing up its temp then dissconnecting (not connected) then flashing up again maybe every 500ms 

have i done someting wrong i am happt for it to be there (would pefer it not to be ) but it disconnecting etc would love to stop

![Screenshot 2023-12-08 204045](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/112808604/7b8f9da4-423d-48dd-b872-918620a19e98)
![Screenshot 2023-12-08 204036](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/112808604/0e15d23d-7c02-4abf-b270-4cd248feb131)

**Comment by Rikkert-RS** [comment]
Hello,

this is a strange behavior.
Do you have connected any temperature sensors to pin 26?
Is Pin26 free or is there something else connected there?

Can you view the log file via SSH:
/data/log/VenusOS-TemperatureService/current

**Comment by Sarah-1331** [comment]
pin 26 is free at the moment sensors due for delivery tomorow

**Comment by Rikkert-RS** [comment]
Is it still flashing?

Can you read out the log file for me?

**Comment by Rikkert-RS** [comment]
Apparently the service crashes at some point, but very difficult to check without a log file

**Comment by Sarah-1331** [comment]
I will do thanks for helping I’ll update tomorrow

**Comment by Sarah-1331** [comment]
hi thanks for the help 

when i ssh i get permission denied 



so i have connected temp sensor to gpio26 
and it doesnt show also the pi cpu is still flashing then dissconnecting 

here is the log from /data/log/tempservice/current
```
@40000000657871ea042fc124     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871ea05b53074 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871eb1e6889cc INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871eb1e70907c INFO:root:Loglevel set to INFO
@40000000657871eb1fb6ef44 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871eb1fb70e84 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871eb1fb7220c INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871eb2d779084 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871eb2d7faabc INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871eb2d897a74 INFO:root:cpu temperature interface connected
@40000000657871eb2e426264 Traceback (most recent call last):
@40000000657871eb2e4279d4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871eb2e428d5c     update()
@40000000657871eb2e429144   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871eb2e42a4cc     update_W1()
@40000000657871eb2e42a8b4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871eb2e42bc3c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871eb2e445e34 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871ec2fe5d54c INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871ec2fecbed4 INFO:root:Loglevel set to INFO
@40000000657871ec3084f794 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871ec30b79884 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871ec30c154b4 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871ec348acc4c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871ec349280f4 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871ec349c0e44 INFO:root:cpu temperature interface connected
@40000000657871ec3548adac Traceback (most recent call last):
@40000000657871ec3548d0d4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871ec3548e074     update()
@40000000657871ec3548e844   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871ec3549039c     update_W1()
@40000000657871ec35490b6c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871ec35491ef4     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871ec354aa97c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871ed342a1a64 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871ed34312714 INFO:root:Loglevel set to INFO
@40000000657871ed34f3c364 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871ed352b7d04 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871ed35350a54 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871ed37f2ab84 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871ed37fab234 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871ed38042bfc INFO:root:cpu temperature interface connected
@40000000657871ed3892df3c Traceback (most recent call last):
@40000000657871ed3892f6ac   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871ed38930a34     update()
@40000000657871ed38931204   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871ed389321a4     update_W1()
@40000000657871ed38932974   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871ed38933914     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871ed3895b9b4 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871ee38dc732c INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871ee38e3974c INFO:root:Loglevel set to INFO
@40000000657871ee39edf6b4 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871ee3a1eb344 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871ee3a26d934 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871ef01647fac INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871ef016c3454 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871ef01759a94 INFO:root:cpu temperature interface connected
@40000000657871ef01ff601c Traceback (most recent call last):
@40000000657871ef01ff7b74   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871ef01ff8b14     update()
@40000000657871ef01ff92e4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871ef01ffa66c     update_W1()
@40000000657871ef01ffaa54   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871ef01ffbddc     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871ef02014094 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f0007f47fc INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f0008654ac INFO:root:Loglevel set to INFO
@40000000657871f001688ad4 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f0019c9324 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f001a447cc INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f004a1e3e4 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f004a9a444 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f004b3069c INFO:root:cpu temperature interface connected
@40000000657871f0051ec4a4 Traceback (most recent call last):
@40000000657871f0051edc14   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f0051eef9c     update()
@40000000657871f0051ef76c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f0051f070c     update_W1()
@40000000657871f0051f0edc   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f0051f1e7c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f00523d19c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f1040b5104 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f1041b4ec4 INFO:root:Loglevel set to INFO
@40000000657871f104bfb4b4 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f1052a70ec INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f10536f7f4 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f1081413bc INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f1081d146c INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f10826ff7c INFO:root:cpu temperature interface connected
@40000000657871f108b47654 Traceback (most recent call last):
@40000000657871f108b48dc4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f108b4a14c     update()
@40000000657871f108b4a91c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f108b4b8bc     update_W1()
@40000000657871f108b4c08c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f108b4d02c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f108b7b65c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f2078ce644 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f2079448e4 INFO:root:Loglevel set to INFO
@40000000657871f2089a3b7c INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f208ca8aac INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f208d39afc INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f20b8d2d1c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f20b952814 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f20b9ec11c INFO:root:cpu temperature interface connected
@40000000657871f20c485344 Traceback (most recent call last):
@40000000657871f20c486ab4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f20c487e3c     update()
@40000000657871f20c48860c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f20c4895ac     update_W1()
@40000000657871f20c489d7c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f20c48ad1c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f20c4a33bc FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f30b0c8f54 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f30b18d3f4 INFO:root:Loglevel set to INFO
@40000000657871f30bc18f44 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f30c2d5134 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f30c351194 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f30f07f044 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f30f0f85ac INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f30f18efd4 INFO:root:cpu temperature interface connected
@40000000657871f30fb2c6a4 Traceback (most recent call last):
@40000000657871f30fb2e5e4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f30fb2f96c     update()
@40000000657871f30fb2fd54   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f30fb310dc     update_W1()
@40000000657871f30fb314c4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f30fb3284c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f30fb4ddcc FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f40eb10a2c INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f40ebbb4a4 INFO:root:Loglevel set to INFO
@40000000657871f40f52533c INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f40f89786c INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f40f974794 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f41322181c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f413313734 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f4133da2e4 INFO:root:cpu temperature interface connected
@40000000657871f413c0a20c Traceback (most recent call last):
@40000000657871f413c0b97c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f413c0cd04     update()
@40000000657871f413c0d4d4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f413c0e474     update_W1()
@40000000657871f413c0ec44   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f413c0fbe4     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f413c2672c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f512b88c94 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f512c31bb4 INFO:root:Loglevel set to INFO
@40000000657871f513592dac INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f513915c7c INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f5139ec9fc INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f51708c05c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f51713bcdc INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f5171ef7dc INFO:root:cpu temperature interface connected
@40000000657871f517951624 Traceback (most recent call last):
@40000000657871f51795317c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f51795411c     update()
@40000000657871f5179548ec   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f51795588c     update_W1()
@40000000657871f51795605c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f5179573e4     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f51796a87c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f6169201ec INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f6169da27c INFO:root:Loglevel set to INFO
@40000000657871f6173b2a9c INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f61770a604 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f61778721c INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f61aca21a4 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f61ad1ca94 INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f61adb7b0c INFO:root:cpu temperature interface connected
@40000000657871f61b6c87dc Traceback (most recent call last):
@40000000657871f61b6c9f4c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f61b6cb2d4     update()
@40000000657871f61b6cbaa4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f61b6cca44     update_W1()
@40000000657871f61b6cd214   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f61b6ce1b4     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f61b6e740c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f71b0624ec INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f71b0d319c INFO:root:Loglevel set to INFO
@40000000657871f71b9fccdc INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f71bd3488c INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f71bdc9374 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f71eb67704 INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f71ebe5a8c INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f71ec9d024 INFO:root:cpu temperature interface connected
@40000000657871f71f433644 Traceback (most recent call last):
@40000000657871f71f434db4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f71f43613c     update()
@40000000657871f71f43690c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f71f4378ac     update_W1()
@40000000657871f71f43807c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f71f43901c     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f71f44d454 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f81e3a172c INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f81e4156a4 INFO:root:Loglevel set to INFO
@40000000657871f81edc94d4 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f81f11cdd4 INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f81f1edd94 INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f82237838c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f8224239bc INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f8224d3254 INFO:root:cpu temperature interface connected
@40000000657871f822ceed44 Traceback (most recent call last):
@40000000657871f822cf0c84   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f822cf1c24     update()
@40000000657871f822cf23f4   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f822cf3394     update_W1()
@40000000657871f822cf3b64   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f822cf4eec     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f822d0be1c FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves'
@40000000657871f921954464 INFO:root:/data/VenusOS-TemperatureService/dbus-i2c.py is starting up - python 3
@40000000657871f9219fcbb4 INFO:root:Loglevel set to INFO
@40000000657871f92237fca4 INFO:root:registered ourselves on D-Bus as com.victronenergy.temperature.RPi_cpu_id01
@40000000657871f92270e30c INFO:root:Add setting /Settings/Temperature/1/TemperatureType [0, 0, 3]
@40000000657871f9227e67fc INFO:root:Add setting /Settings/Temperature/1/CustomName ['', 0, 0]
@40000000657871f92575419c INFO:root:Retreived setting /Settings/Temperature/1/TemperatureType /TemperatureType 0
@40000000657871f9257fc8ec INFO:root:Retreived setting /Settings/Temperature/1/CustomName /CustomName 
@40000000657871f9258abd9c INFO:root:cpu temperature interface connected
@40000000657871f92601f524 Traceback (most recent call last):
@40000000657871f926021464   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 408, in <module>
@40000000657871f926022404     update()
@40000000657871f926022fbc   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 59, in update
@40000000657871f926023f5c     update_W1()
@40000000657871f92602472c   File "/data/VenusOS-TemperatureService/dbus-i2c.py", line 155, in update_W1
@40000000657871f9260256cc     fd = open('/sys/devices/w1_bus_master1/w1_master_slaves','r')
@40000000657871f926042f74 FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/w1_bus_master1/w1_master_slaves
```

**Comment by Rikkert-RS** [comment]
Hello sarah1331sarah,

OK, that helps, I can already see the problem.
First of all, it is because there is no temp sensor connected and some 1Wire Folder does not exist.

But I can't look at it until tomorrow.

But you can just write to me how you connected the sensors to Pin26. Because with sensor the error shouldn't occur

best regards

**Comment by Sarah-1331** [comment]
data wire direct to pin 37 GPIO26 5v to red gnd to black

**Comment by Rikkert-RS** [comment]
no pullup?

you need a 4,7kOhm pullup from 5V to Data Pin

**Comment by Sarah-1331** [comment]
will try that now sorry for my stupidity

**Comment by Sarah-1331** [comment]
still nothing shown i think its the file and folder ?

**Comment by Rikkert-RS** [comment]
https://github.com/Rikkert-RS/VenusOS-TemperatureService/issues/7#issuecomment-1596296044

There are some pictures with 1Wire connection

But there is still an error if no sensor is connected and only the CPU temp is used. I will fix the error tomorrow

**Comment by Sarah-1331** [comment]
i have the 4.7k now i was going to ask if i add more do i need to adjust the value but #7 shows i dont thanks again 

the cpu temp shows then "disconnects" then shows etc 

if i knew the file its requesting i can make the folder and add it ?


can i take the time here to show my apreacation for you help

**Comment by Rikkert-RS** [comment]
> still nothing shown i think its the file and folder ?

Which type of sensor you using?

**Comment by Sarah-1331** [comment]
DS18B20

**Comment by Sarah-1331** [comment]
i have just started again with my test pi3 and its now working hopefully its notsomethig else i install from the setuphelper conflicting

**Comment by Rikkert-RS** [comment]
Ok sensortyp is ok.

Is there perhaps a similar folder like this?

 /sys/devices/w1_bus_master1/w1_master_slaves

**Comment by Sarah-1331** [comment]
yes w1_bus_master1 but its just gone again after installing items from setup helper i will install 1 by 1 and find the conflict

**Comment by Rikkert-RS** [comment]
Which version of Temp Service is installed in your setup helper?

If you had previously installed a very old version, I would have an idea why it doesn't work

**Comment by Sarah-1331** [comment]
0.51 if i remove gpio its fine.. arrrrgggghhhhhh

**Comment by Rikkert-RS** [comment]
OK, that sounds like a GPIO conflict.

I have to check it on the PC

I'll let you know when I know more

**Comment by Sarah-1331** [comment]
100% is if i edit setup to make it run on gpio4 it works again with GPIOsetup 
although i need 4 for rtc lol ill get there am sure

**Comment by Sarah-1331** [comment]
thanks again changed setup 
```
        echo "#### Change 1-Wire Temperatursensor on Pin20"  >> "$configFile"
		echo "dtoverlay=w1-gpio,gpiopin=20" >> "$configFile"
		echo "#### end change 1-Wire Pin20" >> "$configFile"
        filesUpdated=true
    fi
	
fi

#### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling VenusOS Temperature Service"

    removeService $packageName
	
	restoreActiveFile "$overlayFile"
	
	# remove mods from configFile - do not use restore in case other mods were made manually
    if [ -f "$configFile" ]; then
        if [ $(grep -c "#### Change 1-Wire Temperatursensor on Pin20" "$configFile") != 0 ]; then
            sed -i -e '/#### Change 1-Wire Temperatursensor on Pin20/,/#### end change 1-Wire Pin20/d' "$configFile"
```

no conflicts at all 


thank you again

**Comment by Rikkert-RS** [comment]
I'm back on the PC now, but I can no longer understand your current configuration exactly.

1. Which software packages do you still have installed next to TemperatureService with or without Setup Helper? 
2. How is the sensor connected now?
3. Do I understand correctly that it is now working for you?

I have solved the problem with crashing service on my Testsetup with no sensors connected.
But I will only create a new version if the discussion indicates that no further changes are necessary

Unfortunately, there are always conflicts with the GPIOs and Addon's, which is unfortunately normal and difficult to solve.

!!! Important !!!
if you want to change the GPIO you don't need to edit the Setup File and reinstall. 
(This setting also survives an TemperatureService update but not an Venus OS update)

Goto /u-boot/config.txt

and Change only the Pin Number . Do not change the text that begins with ####

```
#### Change 1-Wire Temperatursensor on Pin26
dtoverlay=w1-gpio,gpiopin=26 <----- just make changes here
#### end change 1-Wire Pin26

```

**Comment by Sarah-1331** [comment]
Ah so I have everything working I ended up changing the setup I didn’t know I could change the config.txt thank you now I know for future 

settled on pin 20 as gpio setup doesn’t use this pin either 
I have just done a firmware update and it survived 

perfect

**Comment by Rikkert-RS** [comment]
OK fine

Now i Understand that you use rpigpiosetup from Setup Helper

Here is another soleved issue with the same topic. I'll probably add this to the readme as a note.
https://github.com/Rikkert-RS/VenusOS-TemperatureService/issues/5#issuecomment-1556277827

I will immediately create version v0.52 with the fix.
If you change the setup file it will survive a Venus OS update a change in uboot/config.txt not but in principle, both are possible
In the future I plan to bring the port setup into the Gui

nice that it works now.

**Comment by Rikkert-RS** [comment]
@sarah1331sarah if you want you can try v0.52. It should now run with and without sensors.
It is on Setup Helper ready for install / update. After Update check your GPIO in Config.txt is still 20.

**Comment by Sarah-1331** [comment]
all working perfect thanks again
